### ISSUE TITLE
GOAL: Make a component for the Map

### ISSUE THREAD

**Issue by ecumene** [CameronMellis/aviation-weather#9]
## Usage:
`<Map location="YUL" />`

## Details 
 - Uses the location as the source of its images
 - Has buttons and options to change time

## Code
![Screen Shot 2022-04-03 at 3 57 19 PM](https://user-images.githubusercontent.com/6249465/161442610-8440d350-1d35-4015-bf6d-01d164c45f66.png)

**Comment by CameronMellis** [comment]
nice
